export const ErrorCode = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_JSON: "INVALID_JSON",
  MISSING_FIELD: "MISSING_FIELD",
  INVALID_FORMAT: "INVALID_FORMAT",
  PASSWORD_TOO_SHORT: "PASSWORD_TOO_SHORT",

  UNAUTHORIZED: "UNAUTHORIZED",
  MISSING_TOKEN: "MISSING_TOKEN",
  INVALID_TOKEN: "INVALID_TOKEN",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",

  FORBIDDEN: "FORBIDDEN",
  MISSING_PERMISSION: "MISSING_PERMISSION",
  ACCOUNT_BANNED: "ACCOUNT_BANNED",

  NOT_FOUND: "NOT_FOUND",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  THREAD_NOT_FOUND: "THREAD_NOT_FOUND",

  CONFLICT: "CONFLICT",
  EMAIL_EXISTS: "EMAIL_EXISTS",

  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  INVALID_EXCHANGE_CODE: "INVALID_EXCHANGE_CODE",
  INVALID_RESET_TOKEN: "INVALID_RESET_TOKEN",

  AUTH_OAUTH_FAILED: "AUTH_OAUTH_FAILED",
  AUTH_GOOGLE_FAILED: "AUTH_GOOGLE_FAILED",

  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
